stages:
    - deploy

variables:
    LANG: "en_US.UTF-8"
    LC_ALL: "en_US.UTF-8"
    GIT_SUBMODULE_STRATEGY: normal

beta:
    tags:
        - beta
    stage: deploy
    only:
        - master
    except:
        - tags
    script:
        - fastlane beta
    environment:
        name: internal


alpha:
    tags:
        - alpha
    stage: deploy
    only:
        - master
    except:
        - tags
    script:
        - fastlane alpha
    environment:
        name: internal
