stages:
    - deploy

variables:
    LANG: "en_US.UTF-8"
    LC_ALL: "en_US.UTF-8"
    GIT_SUBMODULE_STRATEGY: recursive
    GIT_STRATEGY: fetch


beta:
    tags:
        - beta
    stage: deploy
    only:
        - master
    except:
        - tags
    script:
        - bash ./buildbox/beta.sh
    environment:
        name: internal
