before_script:
    - eval $(ssh-agent -s)
    - echo ssh-add ~/.ssh/id_rsa

stages:
    - deploy

variables:
    LANG: "en_US.UTF-8"
    LC_ALL: "en_US.UTF-8"
    GIT_SUBMODULE_STRATEGY: recursive
    GIT_STRATEGY: fetch


beta:
    tags:
        - beta
    stage: deploy
    only:
        - beta
    except:
        - tags
    script:
        - bash ./buildbox/sync-toolbox.sh
        - bash ./buildbox/internal.sh beta
    environment:
        name: internal

alpha:
    tags:
        - beta
    stage: deploy
    only:
        - alpha
    except:
        - tags
    script:
        - bash ./buildbox/sync-toolbox.sh
        - bash ./buildbox/internal.sh alpha
    environment:
        name: internal
